/*
 * Tester Interface Main Window  Rev7.0
 *  12/7/2016
 *  author: DMH
 */
package com.detex;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.io.*;
import java.util.logging.*;
import java.util.logging.Logger;
import javax.swing.*;
import org.apache.commons.io.*;
import static java.lang.System.out;

/**
 * Main Interface GUI
 *
 * @author dmh
 */
public class InterfaceGUI extends JFrame {

private static void SHOW_DIALOG (String msg) {
		SwingUtilities.invokeLater(new Runnable() {
		@Override
		public void run () {
				JOptionPane.showMessageDialog(null, msg);
		}
		});
}

/**
 * Creates new form SnapFrame
 */
public InterfaceGUI () {
		initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        jDeviceLabel = new javax.swing.JLabel();
        jUserInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextScreen = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAdvanced = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemShowLog = new javax.swing.JMenuItem();
        jMenuItemShowSettings = new javax.swing.JMenuItem();
        jMenuItemClearScreen = new javax.swing.JMenuItem();
        jMenuDevice = new javax.swing.JMenu();
        jMenuItemEAX300 = new javax.swing.JMenuItem();
        jMenuV40 = new javax.swing.JMenu();
        jMenuItemV40xx00 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuEAX2500 = new javax.swing.JMenu();
        jMenuItem2500 = new javax.swing.JMenuItem();
        jMenuItem2503 = new javax.swing.JMenuItem();
        jMenuItem2504 = new javax.swing.JMenuItem();
        jMenuItem2505 = new javax.swing.JMenuItem();
        jMenuItem2510 = new javax.swing.JMenuItem();
        jMenuItem2513 = new javax.swing.JMenuItem();
        jMenuItem2514 = new javax.swing.JMenuItem();
        jMenuItem2520 = new javax.swing.JMenuItem();
        jMenuItem2523 = new javax.swing.JMenuItem();
        jMenuItem2524 = new javax.swing.JMenuItem();
        jMenuItem2544 = new javax.swing.JMenuItem();
        jMenuItem2545 = new javax.swing.JMenuItem();
        jMenuEAX500 = new javax.swing.JMenu();
        jMenuItem500 = new javax.swing.JMenuItem();
        jMenuItem503 = new javax.swing.JMenuItem();
        jMenuItem504 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItemEAX3500 = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemVersion = new javax.swing.JMenuItem();
        jMenuItemChangelog = new javax.swing.JMenuItem();
        jMenuLabel = new javax.swing.JMenu();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tester Interface v7.0");
        setBackground(java.awt.Color.orange);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(700, 600));
        setName("frame"); // NOI18N

        progButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        progButton.setText("Program");
        progButton.setToolTipText("Press to begin programming a device");
        progButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        progButton.setBorderPainted(false);
        progButton.setEnabled(false);
        progButton.setIconTextGap(2);
        progButton.addActionListener(formListener);

        testButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        testButton.setText("Test");
        testButton.setToolTipText("Click to begin testing the device");
        testButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        testButton.setBorderPainted(false);
        testButton.setEnabled(false);
        testButton.setIconTextGap(6);

        jDeviceLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDeviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDeviceLabel.setText("Select a device to begin");
        jDeviceLabel.setToolTipText("Current Device");
        jDeviceLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jDeviceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jUserInfoLabel.setBackground(java.awt.SystemColor.windowText);
        jUserInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUserInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserInfoLabel.setText("Not Logged In");
        jUserInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextScreen.setEditable(false);
        jTextScreen.setBackground(new java.awt.Color(51, 153, 255));
        jTextScreen.setColumns(20);
        jTextScreen.setFont(new java.awt.Font("Monospaced", 1, 15));
        jTextScreen.setForeground(new java.awt.Color(255, 255, 255));
        jTextScreen.setLineWrap(true);
        jTextScreen.setRows(5);
        jTextScreen.setText("TODO: Load testing setup instructions here...\n\nBlah\nBlah\nBlah\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nBlah!!!");
        jTextScreen.setToolTipText("");
        jTextScreen.setWrapStyleWord(true);
        jTextScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextScreen);

        jMenuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jMenuBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jMenuFile.setText("File");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(formListener);
        jMenuFile.add(jMenuItemLogout);
        jMenuFile.add(jSeparator);

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(formListener);
        jMenuItemQuit.addMenuKeyListener(formListener);
        jMenuFile.add(jMenuItemQuit);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.addActionListener(formListener);

        jMenuItemAdvanced.setText("Advanced");
        jMenuItemAdvanced.addActionListener(formListener);
        jMenuEdit.add(jMenuItemAdvanced);
        jMenuEdit.add(jSeparator2);

        jMenuItemShowLog.setText("Show Log");
        jMenuItemShowLog.addActionListener(formListener);
        jMenuEdit.add(jMenuItemShowLog);

        jMenuItemShowSettings.setText("Show Settings");
        jMenuItemShowSettings.addActionListener(formListener);
        jMenuEdit.add(jMenuItemShowSettings);

        jMenuItemClearScreen.setText("Clear Screen");
        jMenuItemClearScreen.addActionListener(formListener);
        jMenuEdit.add(jMenuItemClearScreen);

        jMenuBar.add(jMenuEdit);

        jMenuDevice.setText("Device");
        jMenuDevice.addActionListener(formListener);

        jMenuItemEAX300.setText("EAX300");
        jMenuItemEAX300.addActionListener(formListener);
        jMenuDevice.add(jMenuItemEAX300);

        jMenuV40.setText("V40");

        jMenuItemV40xx00.setText("V40xx00");
        jMenuItemV40xx00.addActionListener(formListener);
        jMenuV40.add(jMenuItemV40xx00);

        jMenuItem4.setText("V40xx01");
        jMenuV40.add(jMenuItem4);

        jMenuItem7.setText("V40xx00");
        jMenuItem7.addActionListener(formListener);
        jMenuV40.add(jMenuItem7);

        jMenuItem8.setText("V40xx00");
        jMenuItem8.addActionListener(formListener);
        jMenuV40.add(jMenuItem8);

        jMenuItem9.setText("V40xx00");
        jMenuItem9.addActionListener(formListener);
        jMenuV40.add(jMenuItem9);

        jMenuItem10.setText("V40xx00");
        jMenuItem10.addActionListener(formListener);
        jMenuV40.add(jMenuItem10);

        jMenuItem11.setText("V40xx00");
        jMenuItem11.addActionListener(formListener);
        jMenuV40.add(jMenuItem11);

        jMenuDevice.add(jMenuV40);

        jMenuEAX2500.setText("EAX2500");

        jMenuItem2500.setText("EAX2500");
        jMenuItem2500.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2500);

        jMenuItem2503.setText("EAX2503");
        jMenuEAX2500.add(jMenuItem2503);

        jMenuItem2504.setText("EAX2504");
        jMenuItem2504.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2504);

        jMenuItem2505.setText("EAX2505");
        jMenuEAX2500.add(jMenuItem2505);

        jMenuItem2510.setText("EAX2510");
        jMenuItem2510.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2510);

        jMenuItem2513.setText("EAX2513");
        jMenuItem2513.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2513);

        jMenuItem2514.setText("EAX2514");
        jMenuEAX2500.add(jMenuItem2514);

        jMenuItem2520.setText("EAX2520");
        jMenuItem2520.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2520);

        jMenuItem2523.setText("EAX2523");
        jMenuEAX2500.add(jMenuItem2523);

        jMenuItem2524.setText("EAX2524");
        jMenuEAX2500.add(jMenuItem2524);

        jMenuItem2544.setText("EAX2544");
        jMenuItem2544.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2544);

        jMenuItem2545.setText("EAX2545");
        jMenuItem2545.addActionListener(formListener);
        jMenuEAX2500.add(jMenuItem2545);

        jMenuDevice.add(jMenuEAX2500);

        jMenuEAX500.setText("EAX500");

        jMenuItem500.setText("EAX500");
        jMenuItem500.setActionCommand("EAX500");
        jMenuItem500.addActionListener(deviceActionListener);
        jMenuEAX500.add(jMenuItem500);

        jMenuItem503.setText("EAX503");
        jMenuEAX500.add(jMenuItem503);

        jMenuItem504.setText("EAX504");
        jMenuEAX500.add(jMenuItem504);

        jMenuItem18.setText("EAX505");
        jMenuEAX500.add(jMenuItem18);

        jMenuItem19.setText("EAX510");
        jMenuEAX500.add(jMenuItem19);

        jMenuItem20.setText("EAX513");
        jMenuEAX500.add(jMenuItem20);

        jMenuItem21.setText("EAX514");
        jMenuEAX500.add(jMenuItem21);

        jMenuItem23.setText("EAX515");
        jMenuEAX500.add(jMenuItem23);

        jMenuItem22.setText("EAX520");
        jMenuEAX500.add(jMenuItem22);

        jMenuItem24.setText("EAX524");
        jMenuEAX500.add(jMenuItem24);

        jMenuItem25.setText("EAX525");
        jMenuEAX500.add(jMenuItem25);

        jMenuDevice.add(jMenuEAX500);

        jMenuItemEAX3500.setText("EAX3500");
        jMenuItemEAX3500.setEnabled(false);
        jMenuDevice.add(jMenuItemEAX3500);

        jMenuBar.add(jMenuDevice);

        jMenuAbout.setText("About");

        jMenuItemVersion.setText("Version");
        jMenuAbout.add(jMenuItemVersion);

        jMenuItemChangelog.setText("Changelog");
        jMenuAbout.add(jMenuItemChangelog);

        jMenuBar.add(jMenuAbout);

        jMenuLabel.setText(" :: No Device Selected");
        jMenuLabel.setEnabled(false);
        jMenuBar.add(jMenuLabel);

        setJMenuBar(jMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(progButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(testButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 329, Short.MAX_VALUE)
                .add(jDeviceLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jUserInfoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(progButton)
                        .add(testButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jDeviceLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jUserInfoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jDeviceLabel, jUserInfoLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] {progButton, testButton}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, javax.swing.event.MenuKeyListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == progButton) {
                InterfaceGUI.this.progButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemLogout) {
                InterfaceGUI.this.jMenuItemLogoutActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemQuit) {
                InterfaceGUI.this.jMenuItemQuitActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuEdit) {
                InterfaceGUI.this.jMenuEditActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemAdvanced) {
                InterfaceGUI.this.jMenuItemAdvancedActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemShowLog) {
                InterfaceGUI.this.jMenuItemShowLogActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemShowSettings) {
                InterfaceGUI.this.jMenuItemShowSettingsActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemClearScreen) {
                InterfaceGUI.this.jMenuItemClearScreenActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuDevice) {
                InterfaceGUI.this.jMenuDeviceActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemEAX300) {
                InterfaceGUI.this.jMenuItemEAX300ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemV40xx00) {
                InterfaceGUI.this.jMenuItemV40xx00ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem7) {
                InterfaceGUI.this.jMenuItem7ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem8) {
                InterfaceGUI.this.jMenuItem8ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem9) {
                InterfaceGUI.this.jMenuItem9ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem10) {
                InterfaceGUI.this.jMenuItem10ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem11) {
                InterfaceGUI.this.jMenuItem11ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2500) {
                InterfaceGUI.this.jMenuItem2500ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2504) {
                InterfaceGUI.this.jMenuItem2504ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2510) {
                InterfaceGUI.this.jMenuItem2510ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2513) {
                InterfaceGUI.this.jMenuItem2513ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2520) {
                InterfaceGUI.this.jMenuItem2520ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2544) {
                InterfaceGUI.this.jMenuItem2544ActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem2545) {
                InterfaceGUI.this.jMenuItem2545ActionPerformed(evt);
            }
        }

        public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
        }

        public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            if (evt.getSource() == jMenuItemQuit) {
                InterfaceGUI.this.jMenuItemQuitMenuKeyReleased(evt);
            }
        }

        public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

/**
 * Begins the device programming section
 *
 * @param evt
 */
    private void progButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progButtonActionPerformed
				deviceActionListener.actionPerformed(evt);
    }//GEN-LAST:event_progButtonActionPerformed

/**
 * Triggers a logout event
 *
 * @param evt
 */
    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
				deviceActionListener.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdvancedActionPerformed
				deviceActionListener.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemAdvancedActionPerformed

    private void jMenuItemEAX300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEAX300ActionPerformed
				deviceActionListener.actionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEAX300ActionPerformed

    private void jMenuItemQuitMenuKeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItemQuitMenuKeyReleased
				System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitMenuKeyReleased

/**
 * Quit menu item was pressed
 *
 * @param evt
 */
    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
				System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

  private void jMenuItemV40xx00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemV40xx00ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItemV40xx00ActionPerformed

  private void jMenuDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeviceActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuDeviceActionPerformed

  private void jMenuItem2513ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2513ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2513ActionPerformed

  private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem7ActionPerformed

  private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem8ActionPerformed

  private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem9ActionPerformed

  private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem10ActionPerformed

  private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem11ActionPerformed

  private void jMenuItem2544ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2544ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2544ActionPerformed

  private void jMenuItem2545ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2545ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2545ActionPerformed

  private void jMenuItem2504ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2504ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2504ActionPerformed

  private void jMenuItem2510ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2510ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2510ActionPerformed

  private void jMenuItem2520ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2520ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2520ActionPerformed

  private void jMenuItemShowSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowSettingsActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItemShowSettingsActionPerformed

  private void jMenuItem2500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2500ActionPerformed
			deviceActionListener.actionPerformed(evt);
  }//GEN-LAST:event_jMenuItem2500ActionPerformed

  private void jMenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditActionPerformed

  }//GEN-LAST:event_jMenuEditActionPerformed

  private void jMenuItemShowLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowLogActionPerformed
			// Show the current log
			String path = new File("").getAbsolutePath() + File.separator + "resources" + File.separator + "log.txt";
			File f = FileUtils.getFile(path);
			jTextScreen.setText("");
			LineIterator iterator = null;
			try {
					iterator = FileUtils.lineIterator(f);
			} catch (IOException ex) {
					Logger.getLogger(InterfaceGUI.class.getName()).log(Level.SEVERE, null, ex);
					jTextScreen.setText("Error reading log file.");
					return;
			}
			StringBuilder buffer = new StringBuilder();
			while (iterator.hasNext())
					buffer.append(iterator.next()).append("\n");
			jTextScreen.setText(buffer.toString());
			// jTextScreen.setText(jTextScreen.getText() + "\n" + iterator.next());
  }//GEN-LAST:event_jMenuItemShowLogActionPerformed

    private void jMenuItemClearScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearScreenActionPerformed
				jTextScreen.setText("");
    }//GEN-LAST:event_jMenuItemClearScreenActionPerformed

WindowListener listener;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDeviceLabel;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDevice;
    private javax.swing.JMenu jMenuEAX2500;
    private javax.swing.JMenu jMenuEAX500;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    public javax.swing.JMenuItem jMenuItem18;
    public javax.swing.JMenuItem jMenuItem19;
    public javax.swing.JMenuItem jMenuItem20;
    public javax.swing.JMenuItem jMenuItem21;
    public javax.swing.JMenuItem jMenuItem22;
    public javax.swing.JMenuItem jMenuItem23;
    public javax.swing.JMenuItem jMenuItem24;
    public javax.swing.JMenuItem jMenuItem25;
    public javax.swing.JMenuItem jMenuItem2500;
    public javax.swing.JMenuItem jMenuItem2503;
    public javax.swing.JMenuItem jMenuItem2504;
    public javax.swing.JMenuItem jMenuItem2505;
    public javax.swing.JMenuItem jMenuItem2510;
    public javax.swing.JMenuItem jMenuItem2513;
    public javax.swing.JMenuItem jMenuItem2514;
    public javax.swing.JMenuItem jMenuItem2520;
    public javax.swing.JMenuItem jMenuItem2523;
    public javax.swing.JMenuItem jMenuItem2524;
    public javax.swing.JMenuItem jMenuItem2544;
    public javax.swing.JMenuItem jMenuItem2545;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItem500;
    public javax.swing.JMenuItem jMenuItem503;
    public javax.swing.JMenuItem jMenuItem504;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public javax.swing.JMenuItem jMenuItemAdvanced;
    private javax.swing.JMenuItem jMenuItemChangelog;
    private javax.swing.JMenuItem jMenuItemClearScreen;
    public javax.swing.JMenuItem jMenuItemEAX300;
    private javax.swing.JMenuItem jMenuItemEAX3500;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemShowLog;
    public javax.swing.JMenuItem jMenuItemShowSettings;
    private javax.swing.JMenuItem jMenuItemV40xx00;
    private javax.swing.JMenuItem jMenuItemVersion;
    public javax.swing.JMenu jMenuLabel;
    private javax.swing.JMenu jMenuV40;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JTextArea jTextScreen;
    private javax.swing.JLabel jUserInfoLabel;
    private javax.swing.JButton progButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables

DeviceListener deviceActionListener = new DeviceListener();

/**
 * Class for listening for new device selection
 */
class DeviceListener implements ActionListener {

public DeviceListener () {
}

@Override
public void actionPerformed (ActionEvent e) {
		//SHOW_DIALOG(e.getActionCommand());
		// String source = ((JMenuItem) e.getSource()).getName();
		//SHOW_DIALOG();
		selectV40ModelDialog();
		//jTextScreen.setText(jTextScreen.getText() + '\n' + e.getActionCommand());
		//setDevice(e.getActionCommand());
}

void setDevice (String name) {
		//      Deivces d = Devices.valueOf(Devices, name);
		if (name.startsWith("V"))
				selectV40ModelDialog();
}

void selectV40ModelDialog () {
		// Devices.Models[] selectionValues = Devices.Models.values();
		SwingUtilities.invokeLater(new Runnable() {

		@Override
		public void run () {
				//          Devices.Models m = JOptionPane.showInputDialog(JFrame, "Select Model", "Select Model", JOptionPane.PLAIN_MESSAGE, null, selectionValues, selectionValues[0]);
				//          System.err.println(m.name());
				ArrayList<Object> v40models = new ArrayList<Object>();
				for (Models m : Models.values()) {
						v40models.add(m.part);
						JComboBox v40ComboBox = new JComboBox(v40models.toArray());
						JPanel panel = new JPanel(new GridLayout(2, 2));
						panel.add(new JLabel("V40 Models:"));
						panel.add(v40ComboBox);
						JOptionPane.showConfirmDialog(null, panel, "Select V40 Model: ", JOptionPane.OK_CANCEL_OPTION);
						// setModel(Models.values()[v40ComboBox.getSelectedIndex()]);
						return;
				}

		}

		});

}

}

}
